const championsData = [
    {
        id: 1,
        name: "Aatrox",
        image: "lien_vers_image_aatrox",
        description: "Aatrox est un guerrier...",
        difficulty: "Élevée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Ahri",
        title: "La renarde à neuf queues",
        image: "lien_vers_image_ahri",
        description: "Ahri est un mage...",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Lux",
        title: "Dame de Lumière",
        image: "lien_vers_image_ahri",
        description: "Luxanna Crownguard est originaire de Demacia, un royaume isolationniste où la magie inspire la peur et la méfiance. Capable de plier la lumière à sa volonté, elle a grandi dans la crainte d'être un jour exilée et a été contrainte de dissimuler son pouvoir pour préserver l'honneur de sa famille. Cependant, l'optimisme et la ténacité de Lux l'ont conduite à accepter ses talents uniques, et elle les emploie désormais secrètement pour le bénéfice de sa patrie.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Maître Yi",
        title: "Fine Lame Wuju",
        image: "lien_vers_image_ahri",
        description: "Maître Yi a renforcé son corps et affûté son esprit jusqu'à ce que réflexion et action ne fassent plus qu'un. Bien qu'il ne fasse appel à la violence qu'en dernier recours, la grâce et la vitesse avec lesquelles il manie son épée assurent une résolution rapide de tout conflit. En tant que l'un des derniers praticiens vivants de l'art martial ionien appelé Wuju, Yi a voué sa vie à perpétuer l'héritage de son peuple, scrutant les nouveaux disciples potentiels à l'aide des Sept lentilles d'éveil pour identifier les plus dignes de recevoir son enseignement.",
        difficulty: "Modérée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Malphite",
        title: "Éclat du Monolithe",
        image: "lien_vers_image_ahri",
        description: "Massive créature de pierre vivante, Malphite lutte pour imposer un ordre sacré dans un monde chaotique. Né pour servir l'obélisque mystique que l'on nomme le Monolithe, il utilisa son incroyable force élémentaire pour protéger son créateur, mais n'y parvint pas. Seul survivant de la destruction qui s'ensuivit, Malphite doit désormais supporter les inconséquences des êtres de chair et trouver un nouveau rôle, digne du dernier survivant de son espèce.",
        difficulty: "Faible",
        category: "Tank",
    },
    {
        id: 2,
        name: "Malzahar",
        title: "Prophète du Néant",
        image: "lien_vers_image_ahri",
        description: "Voyant fanatique ayant dédié son existence à l'unification de toute forme de vie, Malzahar croit fermement que le Néant est la voie du salut de Runeterra. Dans les étendues désertiques de Shurima, il suivit les voix qui murmuraient dans son esprit jusqu'à l'antique cité d'Icathia. Au plus profond des ruines, il plongea le regard dans le cœur noir du Néant et reçut de nouveaux pouvoirs, un nouveau but. Malzahar se considère désormais comme un berger : sa tâche est d'unir ses semblables… ou de libérer les créatures du Néant qui vivent sous terre.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Maokai",
        title: "Tréant Torturé",
        image: "lien_vers_image_ahri",
        description: "Maokai est un immense tréant possédé par la colère, qui combat les horreurs impies des Îles obscures. Il est devenu l'incarnation de la vengeance après la destruction de ses terres par un cataclysme magique, n'échappant lui-même à l'état de mort-vivant que grâce à l'eau de la vie qui l'irrigue. Autrefois, Maokai était un paisible esprit de la nature ; aujourd'hui, il combat avec fureur le fléau mort-vivant qui accable les Îles obscures pour rendre à l'archipel son ancienne beauté.",
        difficulty: "Faible",
        category: "Tank",
    },
    {
        id: 2,
        name: "Milio",
        title: "Douce Flamme",
        image: "lien_vers_image_ahri",
        description: "Milio est un garçon d'Ixtal chaleureux qui, malgré son jeune âge, maîtrise l'Axiome du feu et a découvert le feu guérisseur. Grâce à cette puissance nouvelle, il espère intégrer les Yun Tal, comme sa grand-mère avant lui, et annuler le jugement qui contraint sa famille à l'exil. Après avoir traversé les jungles d'Ixtal pour rejoindre Ixaocan, la capitale, il se prépare à affronter le Vidalion, ignorant tout des épreuves et des dangers qui l'attendent.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Miss Fortune",
        title: "Chasseuse de Primes",
        image: "lien_vers_image_ahri",
        description: "Capitaine de Bilgewater réputée pour sa beauté et crainte pour sa cruauté, Sarah Fortune est une personnalité qui détonne au milieu des criminels endurcis qui arpentent la cité portuaire. Enfant, elle assista au massacre de sa famille par Gangplank, le roi des pillards, et elle prit sa revanche des années plus tard, faisant exploser son navire alors qu'il se trouvait à bord. Ceux qui la sous-estiment découvrent un adversaire imprévisible et séduisant... avant de prendre une ou deux balles dans les entrailles.",
        difficulty: "Faible",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Mordekaiser",
        title: "Revenant de Fer",
        image: "lien_vers_image_ahri",
        description: "Deux fois abattu et trois fois né, Mordekaiser est un chef de guerre brutal venu d'un lointain passé. Il utilise ses pouvoirs nécromantiques pour lier les âmes à une éternité de servitude. Il n'y a plus guère de gens pour se souvenir de ses anciennes conquêtes ou pour connaître l'étendue de ses vrais pouvoirs. Pourtant, certaines âmes antiques en ont gardé la mémoire et craignent le jour où il prétendra de nouveau régner sur les vivants et les morts.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Morgana",
        title: "Déchue",
        image: "lien_vers_image_ahri",
        description: "Déchirée entre ses origines célestes et mortelles, Morgana a enchaîné ses ailes pour appartenir pleinement à l'humanité et abattre sa peine et sa rancœur sur les corrompus et les malhonnêtes. Elle rejette les lois et les traditions qu'elle juge injustes. Terrée dans les recoins obscurs de Demacia, elle préfère se battre pour la vérité – quand d'autres veulent la faire taire – en employant ses boucliers et ses chaînes de feu ténébreux. Plus que tout, Morgana croit fermement que même les proscrits et les parias peuvent un jour se racheter.",
        difficulty: "Faible",
        category: "Mage",
    },
    {
        id: 2,
        name: "Naafiri",
        title: "La Meute de Fer",
        image: "lien_vers_image_ahri",
        description: "À travers le désert de Shurima, un concert de hurlements retentit. C'est l'appel des chiens des sables, ces prédateurs voraces qui se déplacent en meutes et luttent pour la moindre source de nourriture de ces terres stériles. Parmi ces meutes, une se distingue des autres. Elle ne suit pas uniquement ses instincts primitifs : elle est guidée par le pouvoir antique des Darkin.",
        difficulty: "Faible",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Nami",
        title: "Aquamancienne",
        image: "lien_vers_image_ahri",
        description: "Jeune Vastaya des mers, Nami fut la première de la tribu des Marai à quitter les océans et à s'aventurer sur la terre ferme lorsque leur accord ancestral avec les Targoniens fut rompu. Convaincue qu'il n'y avait pas d'autre solution, elle a décidé de suivre le rituel sacré permettant de garantir la protection de son peuple. Plongée en plein chaos, Nami fait face à son avenir avec détermination, utilisant son bâton d'Aquamancienne pour invoquer la puissance des océans.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Nasus",
        title: "Gardien des Sables",
        image: "lien_vers_image_ahri",
        description: "Nasus est un imposant Transfiguré à tête de chacal, une figure héroïque que les peuples du désert considéraient comme un demi-dieu aux temps anciens de Shurima. Il était très intelligent ; son savoir encyclopédique et son extraordinaire sens stratégique guidèrent l'antique empire de Shurima vers la grandeur pendant des siècles. Après la chute de l'empire, il s'imposa un exil et devint peu à peu une légende. Maintenant que l'ancienne cité de Shurima renaît de ses cendres, il est de retour, déterminé à empêcher qu'elle ne chute de nouveau.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Nautilus",
        title: "Titan des Profondeurs",
        image: "lien_vers_image_ahri",
        description: "Nautilus, une légende plus ancienne encore que la première jetée de Bilgewater, est un titan en armure qui sillonne les eaux sombres au large des Îles de la Flamme Bleue. Trahi il y a bien longtemps de cela, il frappe désormais sans prévenir, se servant de son ancre gigantesque pour sauver les malheureux et couler les avares. On raconte qu'il vient chercher ceux qui oublient de payer le « tribut de Bilgewater » et qu'il les emmène avec lui au fond des mers, d'où nul ne peut s'échapper.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Neeko",
        title: "Caméléon Curieux",
        image: "lien_vers_image_ahri",
        description: "Originaire d'une tribu disparue de Vastayas, Neeko est capable de se fondre dans n'importe quelle foule en empruntant l'apparence des autres, allant même jusqu'à absorber un soupçon de leur état émotionnel pour différencier un instant les amis des ennemis. Personne ne sait réellement où – ni qui – peut bien être Neeko, mais ceux qui chercheront à lui faire du mal découvriront bien vite sa véritable nature… et goûteront à toute la force primordiale de son pouvoir spirituel.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Nidalee",
        title: "Chasseresse Bestiale",
        image: "lien_vers_image_ahri",
        description: "Élevée au plus profond de la jungle, Nidalee est une pisteuse d'exception qui peut se transformer à volonté en couguar. Ni totalement femme, ni totalement bête, elle défend férocement son territoire contre tous ceux qui veulent y pénétrer avec ses pièges judicieusement placés et sa lance. Elle estropie sa proie avant de se jeter sur elle sous sa forme de félin. Ceux qui survivent sont rares, et tous la décrivent comme une femme aux griffes aussi aiguisées que ses instincts...",
        difficulty: "Élevée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Nilah",
        title: "Joie Incarnée",
        image: "lien_vers_image_ahri",
        description: "Nilah est une guerrière disciplinée originaire d'une contrée lointaine. Elle traque les monstres les plus gigantesques et les plus dangereux pour les affronter et les détruire. Elle a obtenu son pouvoir du démon de la joie, emprisonné il y a bien longtemps. Cela explique qu'elle ne ressente aucune émotion, à part une joie continue. Le prix à payer est donc très faible en contrepartie de la force extraordinaire qu'elle possède désormais. Elle canalise la forme liquide du démon dans une épée au pouvoir unique et elle s'oppose aux menaces antiques dont le souvenir s'est perdu depuis longtemps.",
        difficulty: "Élevée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Nocturne",
        title: "Éternel Cauchemar",
        image: "lien_vers_image_ahri",
        description: "Expression démoniaque des cauchemars qui hantent tous les êtres doués d'intelligence, la chose que l'on nomme Nocturne est devenue une force primordiale du mal. D'aspect liquide, c'est une ombre sans visage, au regard glacial, armée de lames effrayantes. Après s'être affranchi du royaume des esprits, Nocturne est parvenu jusqu'au monde éveillé, pour se nourrir d'une terreur qui ne prospère que dans les véritables ténèbres.",
        difficulty: "Modérée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Nunu et Willump",
        title: "Le Garçon et Son Yéti",
        image: "lien_vers_image_ahri",
        description: "Il était une fois un jeune garçon qui voulait prouver qu'il était un héros en tuant un monstre effrayant, mais il découvrit que la créature, un yéti solitaire, avait seulement besoin d'un ami. Rapprochés par une puissance ancienne et un amour partagé des boules de neige, Nunu et Willump courent maintenant librement dans tout Freljord en donnant vie à des aventures rêvées. Ils espèrent un jour retrouver la mère disparue de l'enfant. S'ils peuvent la sauver, peut-être seront-ils vraiment des héros, finalement…",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Olaf",
        title: "Berserker",
        image: "lien_vers_image_ahri",
        description: "Olaf, avec sa hache et son extraordinaire force de destruction, ne souhaite que mourir au combat. Venu de l'âpre péninsule freljordienne de Lokfar, il a été choqué par une prophétie qui lui prédisait une mort paisible : dans l'esprit de son peuple, une ignoble fin de lâche. Cherchant la mort et animé par la rage, il ravage une région après l'autre, éliminant des hordes de grands guerriers et de bêtes légendaires dans sa recherche d'un ennemi capable de l'arrêter. Aujourd'hui un brutal combattant de la Griffe hivernale, il espère mourir glorieusement dans les grandes guerres à venir.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Orianna",
        title: "Demoiselle Mécanique",
        image: "lien_vers_image_ahri",
        description: "Autrefois une jeune fille curieuse, de chair et d'os, Orianna est aujourd'hui une merveille de technologie entièrement mécanisée. Elle est tombée gravement malade à la suite d'un accident dans les quartiers inférieurs de Zaun, et son corps défaillant a été remplacé petit à petit par des prothèses perfectionnées. Accompagnée par une sphère extraordinaire qu'elle a elle-même créée pour lui servir de compagnon et de protectrice, Orianna est désormais libre d'explorer la merveilleuse ville de Piltover et ce qui se trouve au-delà.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Ornn",
        title: "Dieu de la Forge Volcanique",
        image: "lien_vers_image_ahri",
        description: "Ornn est le demi-dieu de la forge et de l'artisanat à Freljord. Avec comme seule compagne la solitude, il travaille dans sa forge enfouie au plus profond des cavernes de lave de l'Âtre-foyer. C'est là qu'il fond et purifie les métaux nécessaires à la création d'objets de qualité inimitable. Tandis que d'autres divinités – Volibear avant tout – s'immiscent dans les affaires des mortels, Ornn ne sort de son antre que pour remettre ces déités à leur place, avec son fidèle marteau ou les pouvoirs du volcan lui-même.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Panthéon",
        title: "Lance Éternelle",
        image: "lien_vers_image_ahri",
        description: "Autrefois l'hôte réticent de la Manifestation de la Guerre, Atreus a survécu à la mort de la puissance céleste qui l'habitait, refusant de succomber au coup qui arracha les étoiles mêmes des cieux. Avec le temps, il apprit à accepter le pouvoir de sa mortalité, et la résistance bornée qui y est associée. Atreus s'oppose désormais aux entités divines en tant que Pantheon, ressuscité parmi les mortels, et manie les armes de la Manifestation animées par sa volonté inébranlable sur le champ de bataille.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Poppy",
        title: "Gardienne du Marteau",
        image: "lien_vers_image_ahri",
        description: "Runeterra ne manque pas de braves champions, mais peu peuvent se targuer d'être aussi tenaces que Poppy. Armée du légendaire marteau d'Orlon, faisant deux fois sa taille, cette yordle déterminée cherche depuis d'innombrables années le « héros de Demacia », qui serait le dépositaire légitime de cette arme. En attendant, elle part inlassablement au combat, repoussant les ennemis du royaume à grands coups de marteau.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Pyke",
        title: "Éventreur des Abysses",
        image: "lien_vers_image_ahri",
        description: "Harponneur renommé des quais-abattoirs de Bilgewater, Pyke aurait dû trouver la mort dans le ventre d'une énorme créature marine… et pourtant, il est revenu. À présent, il écume les ruelles sombres de son ancien port d'attache, utilisant ses dons surnaturels pour assassiner brutalement les riches exploiteurs du peuple. Bilgewater, la ville des chasseurs de monstres, est devenue le terrain de chasse d'un monstre.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Qiyana",
        title: "Impératrice des Éléments",
        image: "lien_vers_image_ahri",
        description: "Dans la ville d'Ixaocan, perdue dans la jungle, Qiyana complote pour obtenir au prix du sang le siège révéré des Yun Tal. Dernière dans l'ordre de la succession, elle affronte ceux qui sont sur son chemin avec une absolue confiance en elle et une maîtrise exceptionnelle de la magie élémentaire. La terre elle-même obéit à ses ordres et Qiyana se considère comme la plus grande élémentaliste de l'histoire d'Ixaocan. À ce titre, elle pense mériter, non une ville, mais un empire.",
        difficulty: "Élevée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Quinn",
        title: "Ailes de Demacia",
        image: "lien_vers_image_ahri",
        description: "Quinn est un chevalier-éclaireur d'élite de Demacia qui se spécialise dans les missions d'infiltration en territoire ennemi. Avec son aigle de légende, Valor, elle forme un duo inséparable dont les proies rendent souvent l'âme avant même de comprendre qu'elles affrontaient non pas un, mais deux héros demaciens. D'une grande agilité quand la situation l'impose, Quinn pointe son arbalète sur l'ennemi pendant que Valor survole le terrain et marque les cibles évasives, pour une efficacité meurtrière sur le champ de bataille.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Rakan",
        title: "Charmeur",
        image: "lien_vers_image_ahri",
        description: "Aussi lunatique qu'il est charmeur, Rakan est un trublion vastaya tristement célèbre, et le plus grand danseur guerrier de l'histoire de la tribu Lhotla. Pour les humains qui vivent dans les hautes terres d'Ionia, son nom est depuis longtemps synonyme de festivals endiablés, de fêtes déraisonnables et de musique anarchique. Peu de gens savent cependant que cet histrion ambulant est également le partenaire de Xayah, la rebelle, dont il défend avec ferveur la cause.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Rammus",
        title: "Tatou Blindé",
        image: "lien_vers_image_ahri",
        description: "Beaucoup l'idolâtrent, certains le méprisent, mais tous restent perplexes devant l'énigmatique Rammus. Protégé par une carapace cloutée, il inspire des théories de plus en plus variées sur ses origines : demi-dieu, oracle, simple bête transformée par la magie... Quelle que soit la vérité, Rammus n'est pas très bavard et ne s'arrête pour personne tandis qu'il parcourt le désert de Shurima.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Rek'Sai",
        title: "Traqueuse du Néant",
        image: "lien_vers_image_ahri",
        description: "Rek'Sai est une créature prédatrice – la plus imposante et la plus féroce de son espèce – qui se déplace sous terre pour surprendre ses proies. Sa faim insatiable a ravagé des régions entières de Shurima à l'époque où cet empire était encore florissant. Les marchands et les caravanes armées faisaient des détours de plusieurs kilomètres pour rester loin de ses terres. Dès lors que Rek'Sai vous a repéré, votre sort est scellé. Nul ne peut lui échapper ; elle est la mort qui surgit du sable.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Rell",
        title: "Vierge de Fer",
        image: "lien_vers_image_ahri",
        description: "Changée en arme vivante par les expériences brutales de l'académie de la Rose noire, Rell est aujourd'hui déterminée à détruire Noxus. Son enfance a été particulièrement horrible ; on lui a fait subir des choses atroces afin de perfectionner ses capacités magiques de manipulation du métal... jusqu'à ce qu'elle réussisse à s'échapper en tuant beaucoup de ses ravisseurs au passage. Désormais considérée comme une criminelle, Rell s'attaque aux soldats noxiens tout en recherchant les survivants de son ancienne « académie ». Bien qu'elle défende les faibles, elle tuera sans pitié ses anciens tortionnaires.",
        difficulty: "Faible",
        category: "Tank",
    },
    {
        id: 2,
        name: "Renata Glasc",
        title: "Baronne de la Chimie",
        image: "lien_vers_image_ahri",
        description: "Renata Glasc s'extirpa des cendres de sa maison natale avec son nom et les recherches alchimiques de ses parents pour seules possessions. Au cours des décennies suivantes, elle devint la Baronne de la chimie la plus riche de Zaun et un génie des affaires capable de faire converger les intérêts de tous vers les siens. Travaillez avec elle et vous serez généreusement récompensé. Opposez-vous à elle et vous ne manquerez pas d'occasions de le regretter. Sachez seulement que tout le monde finit par se rallier à elle.",
        difficulty: "Élevée",
        category: "Support",
    },
    {
        id: 2,
        name: "Renekton",
        title: "Dévoreur des Sables",
        image: "lien_vers_image_ahri",
        description: "Originaire du désert brûlant de Shurima, Renekton est un Transfiguré terrifiant animé par la rage. Il était autrefois le guerrier le plus respecté de l'empire de Shurima, dont il avait mené les armées vers la victoire à maintes reprises. Cependant, après la chute de l'empire, Renekton fut enseveli sous les sables. Petit à petit, alors que le monde changeait, il sombra dans la démence. Désormais libre, son unique souhait est de retrouver et de tuer son frère Nasus qui, croit-il dans sa folie, est responsable des siècles qu'il a passés dans les ténèbres.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Rengar",
        title: "Fier Traqueur",
        image: "lien_vers_image_ahri",
        description: "Rengar est un féroce Vastaya chasseur de trophées qui ne vit que pour le frisson de la traque et de l'élimination des proies les plus dangereuses. Il parcourt le monde à la recherche des bêtes les plus féroces, et surtout de Kha'Zix, la créature du Néant qui lui a fait perdre un œil. Rengar ne piste ses proies ni pour la nourriture ni pour la gloire, mais pour la beauté de la poursuite en elle-même.",
        difficulty: "Élevée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Riven",
        title: "Exilée Brisée",
        image: "lien_vers_image_ahri",
        description: "Autrefois soldat d'un régiment de Noxus, Riven est désormais expatriée dans un pays qu'elle avait elle-même tenté d'envahir. Elle s'est naguère élevée dans la hiérarchie grâce à sa force de conviction et à son efficacité brutale : sa récompense fut de commander ses propres troupes, armée d'une épée runique légendaire. Cependant, sur le front ionien, la foi de Riven en sa terre natale a vacillé avant de rompre. Ayant tranché tous ses liens avec l'empire, elle cherche désormais sa place dans un monde blessé, alors même que, d'après les rumeurs, Noxus a retrouvé sa vigueur d'antan…",
        difficulty: "Élevée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Rumble",
        title: "Menace Mécanisée",
        image: "lien_vers_image_ahri",
        description: "Rumble est un jeune inventeur soupe au lait. Ne disposant que de ses deux mains et d'une pile de ferraille, le yordle au tempérament de feu se fabriqua une colossale armure mécanique, dotée d'un arsenal de harpons électrifiés et de roquettes incendiaires. Si certains pouffent devant ses créations sorties tout droit d'une décharge, Rumble n'en a que faire : après tout, c'est lui qui est doté d'un lance-flammes.",
        difficulty: "Élevée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Ryze",
        title: "Mage Runique",
        image: "lien_vers_image_ahri",
        description: "Largement considéré comme l'un des plus puissants sorciers de Runeterra, Ryze est un archimage endurci par les ans qui porte un fardeau incommensurable sur ses épaules. Armé d'une constitution à toute épreuve et d'un vaste arsenal de connaissances mystiques, il consacre sa vie à rassembler les Runes telluriques, les fragments de magie brute qui ont jadis servi à façonner le monde. Ryze doit récupérer ces reliques avant qu'elles ne tombent entre de mauvaises mains, car il sait quel genre d'horreurs elles pourraient déchaîner sur Runeterra.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Samira",
        title: "Rose du Désert",
        image: "lien_vers_image_ahri",
        description: "Toujours en quête de sensations fortes, Samira regarde la mort dans les yeux avec une confiance inébranlable. Après la destruction qui a frappé son foyer shurimien lorsqu'elle était enfant, Samira a trouvé sa véritable vocation à Noxus, où elle s'est forgé une réputation de tête brûlée extrêmement classe qui accepte les missions les plus dangereuses. Munie de deux pistolets à poudre noire et d'une épée personnalisée, Samira s'épanouit lorsque sa vie est en danger et élimine spectaculairement tous ceux qui se mettent en travers de sa route.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Sejuani",
        title: "Fureur du Nord",
        image: "lien_vers_image_ahri",
        description: "Sejuani est l'impitoyable chef de guerre sublimée de la Griffe hivernale, l'une des tribus les plus redoutées de Freljord. La survie de son peuple est une lutte constante et désespérée contre les éléments. Pour résister aux rigueurs de l'hiver, il doit lancer des assauts contre les Noxiens, les Demaciens et les Avarosans. Sejuani mène elle-même la charge des plus dangereux de ces assauts en chevauchant son sanglier drüvask, Bristle, et en agitant son fléau de glace pure pour congeler et réduire en miettes ses ennemis.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Senna",
        title: "Rédemptrice",
        image: "lien_vers_image_ahri",
        description: "Condamnée dès l'enfance à être hantée par la mystérieuse Brume noire, Senna rejoignit un ordre sacré connu sous le nom des Sentinelles de la lumière. Elle combattit vaillamment, avant de périr sous les coups du cruel spectre Thresh et de voir son âme emprisonnée dans sa lanterne. Refusant de perdre espoir, Senna apprit à utiliser la Brume à l'intérieur de la lanterne et revint à la vie, changée à jamais. Brandissant désormais la puissance des ténèbres comme de la lumière, Senna cherche à mettre fin à la Brume noire en la retournant contre elle-même, chaque tir de son arme permettant de libérer les âmes qui y sont perdues.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Séraphine",
        title: "Chanteuse Rêveuse",
        image: "lien_vers_image_ahri",
        description: "Née à Piltover de parents zauniens, Séraphine peut entendre les âmes des autres. Le monde chante pour elle et elle chante pour le monde. Alors que ces sons l'accablaient dans sa jeunesse, elle s'en inspire aujourd'hui et transforme le chaos en symphonie. Elle chante pour les cités sœurs, afin de rappeler à leurs citoyens qu'ils ne sont pas seuls, qu'ils sont plus forts ensemble et que, pour elle, leur potentiel est infini.",
        difficulty: "Faible",
        category: "Mage",
    },
    {
        id: 2,
        name: "Sett",
        title: "Patron",
        image: "lien_vers_image_ahri",
        description: "Sett s'est imposé en tant que chef du monde criminel florissant d'Ionia après la guerre contre Noxus. Bien qu'il ait fait ses débuts de manière modeste dans les arènes de combat de Navori, il s'est rapidement fait une réputation pour sa force sauvage et sa capacité à encaisser tous les coups sans broncher. Après s'être battu pour se faire une place parmi les combattants locaux, Sett s'est hissé au sommet à la force de ses poings pour finalement prendre le contrôle des arènes dans lesquelles il se battait autrefois.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Shaco",
        title: "Bouffon des Ténèbres",
        image: "lien_vers_image_ahri",
        description: "Fabriqué il y a longtemps pour servir de jouet à un prince qui se sentait seul, Shaco est une marionnette enchantée qui se repaît désormais de meurtres et de chaos. Corrompu par la magie noire et la perte de sa chère mission, le pantin autrefois gentil ne se réjouit plus que du malheur des âmes qu'il tourmente. Il utilise ses jouets et ses mauvais tours pour répandre la mort et le sang, ce qui le fait follement rire. Tous ceux qui, la nuit venue, entendent un odieux ricanement savent qu'ils sont la prochaine cible du Bouffon des ténèbres.",
        difficulty: "Élevée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Shen",
        title: "Œil du Crépuscule",
        image: "lien_vers_image_ahri",
        description: "Shen, l'Œil du crépuscule, est le chef d'un groupe secret de guerriers ioniens connu sous le nom de Kinkou. Désireux d'échapper aux méfaits des émotions, des préjugés et de l'ego, il porte un regard désintéressé sur les choses en arpentant le chemin invisible entre le royaume des esprits et le monde physique. Ayant pour mission d'assurer leur équilibre, Shen emploie ses lames d'acier et son énergie arcanique contre ceux qui voudraient le menacer.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Shyvana",
        title: "Demi-Dragon",
        image: "lien_vers_image_ahri",
        description: "Shyvana est une créature dont le cœur palpite au rythme brûlant d'un éclat de rune magique. Bien qu'elle paraisse souvent humanoïde, elle peut se transformer à volonté en un terrifiant dragon, crachant des flammes sur ses ennemis. Après avoir sauvé la vie du prince héritier Jarvan IV, Shyvana sert au sein de sa garde royale, luttant pour être acceptée par le peuple suspicieux de Demacia.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Singed",
        title: "Chimiste Fou",
        image: "lien_vers_image_ahri",
        description: "Singed est un chimiste zaunien d'une intelligence exceptionnelle, prêt à tout pour repousser les limites de la connaissance, y compris y perdre sa santé mentale. Sa folie répond-elle à une logique ? Ses décoctions ont généralement l'effet escompté, mais pour beaucoup, Singed a perdu tout ce qui faisait de lui un être humain, ne laissant dans son sillage qu'une trace nocive et terrifiante.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Sion",
        title: "Colosse Mort-Vivant",
        image: "lien_vers_image_ahri",
        description: "Guerrier sanguinaire d'une époque révolue, Sion était célébré comme un héros à Noxus, pour avoir étouffé un roi de Demacia de ses mains nues. Il était l'objet d'une telle dévotion qu'on lui refusa le repos éternel, en le ramenant à la vie pour continuer à servir son empire. Il massacre sans distinction alliés comme ennemis sur son chemin, prouvant à cette occasion qu'il n'a plus rien d'humain. Son armure rivetée à même la chair, Sion charge sans relâche au combat, luttant entre deux coups de sa puissante hache pour tenter de se remémorer qui il était.",
        difficulty: "Modérée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Sivir",
        title: "Vierge Martiale",
        image: "lien_vers_image_ahri",
        description: "Sivir est une célèbre chasseuse de trésors et capitaine de mercenaires œuvrant dans le désert de Shurima. Armée de sa légendaire lame en croix, elle a triomphé d'innombrables batailles pour les clients prêts à honorer ses tarifs exorbitants. Connue pour sa détermination et son ambition démesurée, elle tire sa fierté des nombreux trésors qu'elle a déterrés dans les tombes les plus périlleuses de Shurima… et revendus au prix fort. Mais le jour où des forces ancestrales se sont éveillées au plus profond de Shurima, Sivir s'est retrouvée tiraillée entre deux destins conflictuels.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Skarner",
        title: "Gardien de Cristal",
        image: "lien_vers_image_ahri",
        description: "Skarner est un immense scorpion cristallin venu d'une vallée cachée de Shurima. Issus de l'ancienne race des Brackerns, Skarner et les siens sont connus pour leur grande sagesse et leurs liens profonds avec la terre : leur âme a fusionné avec de puissants cristaux de vie qui contiennent les pensées et les souvenirs de leurs ancêtres. À une époque si reculée que nul ne s'en souvient, les Brackerns sont entrés en hibernation pour échapper à la destruction magique, mais des événements menaçants viennent de réveiller Skarner. Seul Brackern éveillé, il lutte pour protéger les siens contre ceux qui cherchent à les blesser.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Smolder",
        title: "Dragonnet Flamboyant",
        image: "lien_vers_image_ahri",
        description: "Caché dans les falaises escarpées de la frontière noxienne et attentivement surveillé par sa mère, un jeune dragon apprend ce que signifie être l'héritier de la lignée impériale des dragons camavoriens. Joueur et impatient de grandir, Smolder est prêt à tout pour développer ses nouvelles compétences. Même s'il n'est encore qu'un dragonnet, ses compétences sont déjà impressionnantes : il met aisément le feu à tout ce qui peut brûler.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Sona",
        title: "Virtuose de la Harpe",
        image: "lien_vers_image_ahri",
        description: "Sona est la plus grande virtuose de l'etwahl de Demacia, ne s'exprimant que par ses accords vibrants et gracieux. Ses manières distinguées lui valent d'être appréciée par l'aristocratie, bien que beaucoup soupçonnent ses mélodies envoûtantes de s'apparenter à de la magie, tabou à Demacia. Inaudible pour des étrangers, mais comprise par ses compagnons les plus proches, Sona se sert de ses harmonies pour soigner ses alliés blessés, mais également pour frapper ses ennemis par surprise.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Soraka",
        title: "Enfant des Étoiles",
        image: "lien_vers_image_ahri",
        description: "Voyageuse originaire de dimensions célestes d'au-delà du Mont Targon, Soraka a abandonné son immortalité pour protéger les mortels de leurs instincts violents. Elle cherche à pousser tous ceux qu'elle rencontre à embrasser les vertus de la compassion et de la pitié, allant jusqu'à soigner même ceux qui lui veulent du mal. Et, malgré toutes les souffrances dont Soraka a été témoin dans ce monde, elle croit encore que le peuple de Runeterra n'a pas atteint son plein potentiel.",
        difficulty: "Faible",
        category: "Support",
    },
    {
        id: 2,
        name: "Swain",
        title: "Grand Général Noxien",
        image: "lien_vers_image_ahri",
        description: "Jericho Swain est le chef visionnaire de Noxus, une nation expansionniste qui ne respecte que la force. Bien que déchu et blessé pendant les guerres ioniennes, il a pris le contrôle de l'empire avec une féroce détermination… Et une nouvelle main, démoniaque, a remplacé celle qu'il a perdue au combat. Désormais, Swain dirige ses armées sur la ligne de front, face à des ténèbres qu'il est le seul à percevoir à l'horizon, dans le vol des corbeaux attirés par les cadavres qui l'entourent. Dans un tourbillon de sacrifices et de regrets, le plus grand secret entre tous, c'est que le véritable ennemi est à l'intérieur.",
        difficulty: "Élevée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Sylas",
        title: "Révolutionnaire Déchaîné",
        image: "lien_vers_image_ahri",
        description: "Élevé dans l'un des quartiers les plus pauvres de Demacia, Sylas de Liebourg est devenu le symbole du côté obscur de la Grande cité. Enfant, sa capacité à déceler la sorcellerie cachée attira l'attention des tristement célèbres traqueurs de mages, qui finirent par l'emprisonner pour avoir retourné ses pouvoirs contre eux. Désormais libéré de ses chaînes, Sylas est un révolutionnaire convaincu, employant la magie de ceux qui l'entourent pour ravager le royaume qu'il a autrefois servi… Et son groupe de mages exilés semble grandir chaque jour un peu plus.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Syndra",
        title: "Souveraine Obscure",
        image: "lien_vers_image_ahri",
        description: "Syndra est une effrayante magicienne originaire d'Ionia, aux pouvoirs impressionnants. Enfant, elle perturba les anciens de son village avec sa magie sauvage et incontrôlée. Elle fut confiée à un maître dans l'espoir qu'elle apprendrait à se contrôler, mais elle finit par découvrir que son prétendu mentor limitait ses capacités. Créant des sphères d'énergie noire avec ses sentiments de douleur et de trahison, Syndra jura de détruire quiconque tenterait de la contrôler.",
        difficulty: "Élevée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Tahm Kench",
        title: "Roi des Rivières",
        image: "lien_vers_image_ahri",
        description: "Au fil du temps, on lui a donné de nombreux noms. Le démon Tahm Kench voyage dans les cours d'eau de Runeterra, nourrissant son insatiable appétit de la misère des autres. Bien qu'il puisse sembler particulièrement charmant et fier, il rôde dans le monde tel un vagabond à la recherche d'une proie sans méfiance. Sa langue extensible peut étourdir un guerrier en armure à plusieurs mètres de distance, avant de l'attirer dans son estomac gargouillant vers un abysse dont il n'a que peu de chances de revenir.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Taliyah",
        title: "Tisseuse de Pierres",
        image: "lien_vers_image_ahri",
        description: "Taliyah est une mage issue des tribus nomades de Shurima, déchirée entre l'émerveillement de la jeunesse et les responsabilités des adultes. Elle a déjà traversé pratiquement tout Valoran pour découvrir la véritable nature de ses pouvoirs toujours plus puissants, avant d'être récemment retournée dans sa tribu pour la protéger. Certains se méprennent sur sa compassion et paient leur erreur au prix fort : sous son attitude joviale, Taliyah dissimule une volonté de fer capable de déplacer les montagnes et un esprit assez féroce pour faire trembler la terre.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Talon",
        title: "Lame des Ténèbres",
        image: "lien_vers_image_ahri",
        description: "Talon est la dague cachée dans l'ombre, un assassin impitoyable, capable de frapper sans prévenir et de fuir avant que l'alerte ne soit donnée. Il a acquis une dangereuse réputation dans les brutales rues de Noxus, où il a été contraint de se battre, de tuer et de voler pour survivre. Adopté par la tristement célèbre famille Du Couteau, il use maintenant de ses talents au service de l'empire, assassinant les chefs, capitaines et héros ennemis... mais aussi tout Noxien qui aurait attiré l'ire de ses maîtres.",
        difficulty: "Modérée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Taric",
        title: "Bouclier de Valoran",
        image: "lien_vers_image_ahri",
        description: "Taric est la Manifestation du Protecteur, doté d'un incroyable pouvoir en tant que gardien de la vie, de l'amour et de la beauté sur Runeterra. Couvert d'opprobre pour avoir abandonné son devoir et exilé de sa terre natale de Demacia, Taric a entrepris l'ascension du Mont Targon en quête de rédemption et s'est découvert une mission supérieure au sein des étoiles. Imprégné de la force antique de Targon, le Bouclier de Valoran monte désormais constamment la garde contre la corruption insidieuse du Néant.",
        difficulty: "Faible",
        category: "Support",
    },
    {
        id: 2,
        name: "Teemo",
        title: "Scout de Bantam",
        image: "lien_vers_image_ahri",
        description: "N'ayant pas peur de braver les obstacles les plus dangereux, Teemo explore le monde avec un enthousiasme débordant et une bonne humeur contagieuse. Yordle au sens moral inflexible, il suit fièrement les préceptes du Code des éclaireurs de Bandle, parfois avec tant d'empressement qu'il en oublie les conséquences néfastes de ses actions. Pour certains, l'existence même des éclaireurs est à remettre en cause. Mais ce qu'il ne faut surtout pas remettre en cause, ce sont les convictions de Teemo !",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Thresh",
        title: "Garde aux Chaînes",
        image: "lien_vers_image_ahri",
        description: "Sadique mais rusé, Thresh est un ambitieux esprit des Îles obscures. Autrefois le gardien d'innombrables secrets des arcanes, il fut terrassé par un pouvoir plus grand que la vie ou la mort, et il s'alimente maintenant des souffrances et des tourments qu'il inflige à d'autres avec une inventivité cruelle. Les souffrances de ses victimes ne se limitent pas à leur enveloppe mortelle, car Thresh fait agoniser leurs âmes, les emprisonnant pour l'éternité dans sa lanterne impie.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Tristana",
        title: "Canonnière Yordle",
        image: "lien_vers_image_ahri",
        description: "Si bon nombre d'autres yordles utilisent leur énergie débordante pour explorer, découvrir, inventer ou plus simplement jouer de mauvais tours, Tristana a toujours puisé son inspiration dans les récits des grands guerriers. Elle avait beaucoup entendu parler de Runeterra, de ses factions et de ses guerres, et elle pensait que les yordles aussi avaient l'étoffe des légendes. Dès son arrivée dans ce monde, elle s'équipa de son fidèle canon Boomer pour se jeter au combat avec un courage et un optimisme sans bornes.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Trundle",
        title: "Roi des Trolls",
        image: "lien_vers_image_ahri",
        description: "Trundle est un troll massif, sournois et malicieux. Il n'y a rien qu'il ne puisse soumettre à sa volonté avec son gourdin, pas même Freljord. Extrêmement territorial, Trundle traque tous ceux qui sont assez fous pour pénétrer sur ses terres. Ensuite, armé de son imposante massue en glace pure, il fait trembler ses ennemis avant de leur planter des éclats de glace dans le corps et de se moquer d'eux tandis que la toundra absorbe leur sang.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Tryndamere",
        title: "Roi Barbare",
        image: "lien_vers_image_ahri",
        description: "Poussé par une rage infinie, Tryndamere traverse Freljord et parfait sa maîtrise du combat en défiant les plus grands guerriers du nord, pour se préparer aux jours sombres qui s'annoncent. Longtemps dominé par sa haine, il cherchait à se venger de l'annihilation de son clan, mais il a depuis rencontré Ashe et trouvé un nouveau foyer auprès des Avarosans. Sa force est pratiquement surhumaine et son courage légendaire, et cela lui a permis de remporter avec ses nouveaux alliés d'innombrables victoires plus qu'improbables.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Twisted Fate",
        title: "Maître des Cartes",
        image: "lien_vers_image_ahri",
        description: "Twisted Fate est un virtuose des cartes à la réputation ambiguë qui a parcouru le monde entier pour l'éblouir de son charme et de ses talents, s'attirant l'admiration et la haine des riches comme des pigeons. Il prend rarement les choses au sérieux, salue chaque nouveau jour avec un sourire moqueur et insouciant. Twisted a toujours un atout dans sa manche, au propre comme au figuré.",
        difficulty: "Élevée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Twitch",
        title: "Semeur de Peste",
        image: "lien_vers_image_ahri",
        description: "Rat de Zaun, pesteux de naissance, connaisseur en saleté par passion, Twitch n'a pas peur de se salir les pattes. Armé d'une arbalète chimique qu'il pointe droit sur le cœur de Piltover, Twitch s'est juré de montrer aux gens de la surface à quel point ils sont vraiment sales. Toujours furtif et insaisissable, quand il ne traîne pas dans le Puisard, il fouille dans les déchets à la recherche de trésors qu'il est le seul à apprécier... ou d'un morceau de sandwich.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Udyr",
        title: "Gardien des Esprits",
        image: "lien_vers_image_ahri",
        description: "Udyr est le plus puissant des Gardiens des esprits, il communie avec l'ensemble des esprits qui habitent Freljord. Il comprend leurs besoins avec empathie et il est capable de canaliser et de transformer leur énergie éthérée pour alimenter son propre style de combat primitif. Il cherche l'équilibre intérieur pour que son esprit ne se perde pas parmi les autres, mais il cherche également l'équilibre à l'extérieur, car le paysage mystique de Freljord ne peut prospérer qu'avec la croissance engendrée par le conflit et la lutte. Udyr sait qu'il faut faire des sacrifices pour tenir à distance la stagnation des temps de paix.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Urgot",
        title: "Broyeur",
        image: "lien_vers_image_ahri",
        description: "Autrefois, Urgot était un puissant bourreau noxien. Il fut trahi par l'empire pour lequel il avait tant tué. Ceint de chaînes de fer, il fut contraint d'apprendre le vrai sens de la force dans les Oubliettes, une mine de forçats située dans les profondeurs de Zaun. Il put émerger à l'occasion d'un désastre qui jeta toute la ville dans le chaos. À présent, son ombre imposante s'étend dans son empire criminel souterrain. Levant sur ses victimes les chaînes qui le maintenaient naguère en esclavage, il veut purger son nouveau foyer, nouvelle croisée des douleurs, de tous ceux qu'il en estime indignes.",
        difficulty: "Élevée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Varus",
        title: "Flèche de la Vengeance",
        image: "lien_vers_image_ahri",
        description: "Membre de la race antique des Darkin, Varus était en son temps un assassin cruel qui aimait torturer ses ennemis, les conduisant jusqu'aux portes de la folie avant de les achever d'une flèche. À la fin de la Guerre des Darkin, il fut emprisonné. Des siècles plus tard, il s'évada en utilisant la chair recomposée de deux chasseurs d'Ionia : l'ayant relâché par imprudence, ils furent condamnés à porter l'arc lié à l'essence de Varus. Varus traque désormais ceux qui l'ont enfermé pour se venger, mais les âmes des mortels à l'intérieur de lui s'opposent à ses desseins de toutes leurs forces.",
        difficulty: "Faible",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Vayne",
        title: "Chasseresse Nocturne",
        image: "lien_vers_image_ahri",
        description: "Shauna Vayne est une chasseuse de monstres mortelle et sans scrupule. Originaire de Demacia, elle voue sa vie à la destruction du démon qui a assassiné sa famille. Armée d'une arbalète montée sur son poignet et dotée d'un cœur rongé par le désir de vengeance, elle n'est heureuse que quand elle assassine les praticiens ou les créations des arts obscurs en les frappant depuis l'ombre avec une volée de carreaux d'argent.",
        difficulty: "Élevée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Veigar",
        title: "Seigneur des Maléfices",
        image: "lien_vers_image_ahri",
        description: "Maître enthousiaste de la magie noire, Veigar s'est approprié des pouvoirs que peu de mortels osent approcher. Habitant de Bandle à l'esprit libre, il veut repousser les limites de la magie yordle et se tourner vers les textes arcaniques qui sont restés cachés des millénaires. Fasciné jusqu'à l'obstination par les mystères de l'univers, Veigar est souvent sous-estimé par les gens qui l'entourent. Bien qu'il se croie fondamentalement maléfique, il possède une moralité qui le mène à s'interroger sur ses motivations.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Vel'Koz",
        title: "Œil du Néant",
        image: "lien_vers_image_ahri",
        description: "On ne sait pas trop si Vel'Koz fut le premier monstre du Néant à émerger à Runeterra, mais il est certain qu'aucun autre n'a jamais égalé la froideur calculatrice de sa cruauté. Alors que ses semblables dévorent ou profanent tout ce qui les entoure, il cherche à étudier le royaume physique et les étranges êtres belliqueux qui l'habitent. Selon lui, c'est ainsi que le Néant trouvera comment exploiter leurs faiblesses. Mais Vel'Koz n'est pas qu'un observateur passif. Il répond à toute menace avec des éruptions mortelles de plasma ou en déchirant le tissu même du monde.",
        difficulty: "Élevée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Vex",
        title: "Ombre du désespoir",
        image: "lien_vers_image_ahri",
        description: "Au cœur des terribles Îles obscures et de leur brume spectrale, une yordle solitaire se complaît dans son malheur. Vex se protège de la gaieté, de l'excitation et des gens « normaux » dont le monde extérieur regorge grâce à une dose inépuisable d'apitoiement et à une ombre puissante. Même si l'ambition lui fait défaut, on peut compter sur elle pour ternir le bonheur des autres et éloigner tous ceux qui voudraient l'approcher avec sa morosité magique.",
        difficulty: "Faible",
        category: "Mage",
    },
    {
        id: 2,
        name: "Vi",
        title: "Cogne de Piltover",
        image: "lien_vers_image_ahri",
        description: "Autrefois criminelle des quartiers louches de Zaun, Vi est une femme sans peur, mais pas sans reproche, au tempérament bouillant, impulsive, qui n'a qu'un respect mesuré pour les représentants de l'autorité. Vi a grandi seule et a développé d'excellents instincts de survie ainsi qu'un sens de l'humour assez caustique. Aujourd'hui, elle travaille avec les gendarmes de Piltover pour maintenir l'ordre et se sert pour cela de puissants gantelets Hextech qui n'ont peur de frapper ni les plus épais murs de briques ni les suspects.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Viego",
        title: "Roi Déchu",
        image: "lien_vers_image_ahri",
        description: "Autrefois souverain d'un royaume perdu depuis longtemps, Viego mourut il y a plus de mille ans lorsqu'il tenta de ramener sa femme d'entre les morts. Cela causa la catastrophe magique connue sous le nom de la Ruine. Devenu un puissant spectre torturé par le désir obsessionnel de retrouver sa reine morte depuis des siècles, Viego est désormais le Roi déchu. Il contrôle la Nuit de l'horreur et parcourt Runeterra pour trouver un moyen de ramener sa bien-aimée, détruisant tout sur son passage avec la Brume noire qui se répand inlassablement depuis son cœur brisé et cruel.",
        difficulty: "Modérée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Viktor",
        title: "Héraut des Machines",
        image: "lien_vers_image_ahri",
        description: "Héraut d'un nouvel âge de technologie, Viktor a consacré sa vie aux progrès de l'humanité. Idéaliste cherchant à hisser le peuple de Zaun à de nouveaux sommets de compréhension, il pense que le potentiel de l'humanité ne pourra être réalisé que par le grand pas en avant d'une glorieuse évolution technologique. Doté d'un corps optimisé par l'acier et la science, Viktor poursuit fanatiquement son idéal d'un meilleur avenir.",
        difficulty: "Élevée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Vladimir",
        title: "Saigneur Pourpre",
        image: "lien_vers_image_ahri",
        description: "Assoiffé de sang humain, Vladimir influe sur la politique de Noxus depuis les premiers jours de l'empire. En plus d'allonger surnaturellement sa vie, sa maîtrise de l'hémomancie lui permet de contrôler les esprits et les corps des autres aussi aisément que les siens. Dans les flamboyants salons de l'aristocratie noxienne, cela lui a permis de créer autour de lui un culte de la personnalité. Cependant, dans les bas-fonds, il saigne littéralement ses ennemis à blanc.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Volibear",
        title: "Tempête Impitoyable",
        image: "lien_vers_image_ahri",
        description: "Pour ceux qui le vénèrent encore, Volibear est l'incarnation de la tempête. Destructeur, sauvage et déterminé, il existait bien avant que les mortels n'arpentent la toundra de Freljord ; désormais, il défend férocement les terres qu'il a créées avec sa famille de demi-dieux. Habité d'une haine profonde envers la civilisation et la faiblesse qu'elle a engendrée, il se bat à coups de crocs et de griffes pour restaurer les traditions d'autrefois, celles du temps où la terre était sauvage et où le sang coulait librement.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Warwick",
        title: "Fureur Déchaînée de Zaun", 
        image: "lien_vers_image_ahri",
        description: "Warwick est un monstre qui chasse dans les rues grisâtres de Zaun. Transformé par des expériences horribles, son corps est désormais muni d'un système intriqué de chambres et de pompes qui injecte une rage alchimique dans ses veines. Surgissant des ombres, il traque les criminels qui terrorisent les profondeurs de la ville. Warwick est attiré par le sang, dont l'odeur le rend fou. Si sa proie saigne, elle n'a aucune chance de lui échapper.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Wukong",
        title: "Roi des Singes",
        image: "lien_vers_image_ahri",
        description: "Wukong est un Vastaya qui utilise sa force, son agilité et son intelligence pour semer la confusion parmi ses adversaires et prendre sur eux l'avantage. Après s'être fait un ami en la personne d'un guerrier nommé Maître Yi, Wukong est devenu le dernier tenant d'un art martial antique connu sous le nom de Wuju. Armé de son bâton enchanté, Wukong veut empêcher Ionia de devenir ruines et décombres.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Xayah",
        title: "Rebelle",
        image: "lien_vers_image_ahri",
        description: "Précise et meurtrière, Xayah est une révolutionnaire vastaya menant une guerre personnelle dans le but de sauver son peuple. Elle se sert de sa célérité, de sa ruse et de ses plumes tranchantes comme des rasoirs pour terrasser tous ceux qui se dressent sur sa route. Xayah se bat aux côtés de son partenaire et amant, Rakan, pour défendre leur tribu dépérissante et rendre à leur race ce qu'elle considère être sa gloire d'antan.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Xerath",
        title: "Mage Suprême",
        image: "lien_vers_image_ahri",
        description: "Xerath est un mage transfiguré de la Shurima antique, un être d'énergie arcanique habitant les fragments détruits d'un sarcophage magique. Pendant des millénaires, il est resté prisonnier des sables du désert, mais le retour de Shurima l'a libéré de sa prison ancestrale. Devenu ivre de pouvoir, il cherche désormais à reprendre ce qu'il croit lui être dû et à remplacer les civilisations arrivistes qui ont pris possession du monde par une nouvelle, façonnée à son image.",
        difficulty: "Élevée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Xin Zhao",
        title: "Sénéchal de Demacia",
        image: "lien_vers_image_ahri",
        description: "Xin Zhao est un guerrier résolu qui sert fidèlement la dynastie régnante des Lightshield. Naguère condamné à se battre dans les arènes de combat de Noxus, il survécut à d'innombrables rencontres de gladiateurs. Mais après avoir été libéré par les forces de Demacia, il jura allégeance à ses braves libérateurs. Armé de sa lance à trois pointes, Xin Zhao combat désormais pour son royaume, défiant ses ennemis avec audace, quelles que soient ses chances de succès.",
        difficulty: "Faible",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Yasuo",
        title: "Le Disgracié",
        image: "lien_vers_image_ahri",
        description: "L'Ionien Yasuo est un épéiste agile et résolu, capable de déchaîner contre ses ennemis la puissance de l'air. Alors qu'il était encore un jeune homme fier, il fut accusé à tort d'avoir assassiné son maître. Incapable de prouver son innocence, il dut fuir et fut finalement contraint de tuer son frère pour se défendre. Même après la découverte du véritable meurtrier de son maître, Yasuo ne parvint pas à faire la paix avec sa conscience. Il erre désormais dans son pays natal, et seul le vent guide sa lame.",
        difficulty: "Élevée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Yone",
        title: "Inoublié",
        image: "lien_vers_image_ahri",
        description: "Au cours de sa vie, Yone fut le demi-frère de Yasuo et un disciple renommé de l'école d'armes de son village. Mais après avoir été tué par son propre frère, il se retrouva hanté par une entité malveillante dans le royaume spirituel. Il dut la tuer avec sa propre épée. Désormais maudit et forcé de porter le masque de l'azakana, Yone chasse inlassablement ces créatures démoniaques afin de comprendre ce qu'il est devenu.",
        difficulty: "Élevée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Yorick",
        title: "Berger des Àmes",
        image: "lien_vers_image_ahri",
        description: "Yorick est le dernier survivant d'un ordre religieux disparu depuis longtemps et son pouvoir sur les morts est à la fois une bénédiction et une malédiction. Prisonnier des Îles obscures, il n'a pour compagnons que les cadavres pourrissants et les esprits hurlants qu'il rassemble. Les actes monstrueux de Yorick trahissent son noble objectif : libérer sa terre natale de la malédiction de la Ruine.",
        difficulty: "Modérée",
        category: "Combattant",
    },
    {
        id: 2,
        name: "Yuumi",
        title: "Gardienne du Grimoire",
        image: "lien_vers_image_ahri",
        description: "Originaire de Bandle, Yuumi est un familier magique dont la maîtresse, une enchanteresse yordle du nom de Norra, a mystérieusement disparu. Yuumi est désormais la gardienne du Grimoire des Seuils que possédait Norra, un livre permettant de franchir des portails. Partie à la recherche de sa maîtresse, Yuumi s'est fait de nouveaux amis durant son périple, et elle les protège tous avec la même détermination. Même si Grimoire aimerait que Yuumi se concentre davantage sur sa mission, sa comparse aime prendre le temps de faire la sieste et de pêcher des poissons. Malgré cela, elle finit toujours par repartir en quête de sa maîtresse.",
        difficulty: "Faible",
        category: "Support",
    },
    {
        id: 2,
        name: "Zac",
        title: "Arme Secrète",
        image: "lien_vers_image_ahri",
        description: "Zac est le produit d'une fuite toxique qui, dégoulinant par une veine techno-chimique, se transforma en bassin dans une profonde caverne du Puisard de Zaun. En dépit de ses humbles origines, Zac a évolué pour passer du stade de dépôt primordial à celui d'être pensant qui se faufile dans les canalisations de la ville. De temps en temps, il émerge pour aider ceux qui ne s'en sortent pas seuls ou pour reconstruire les infrastructures en mauvais état de Zaun.",
        difficulty: "Élevée",
        category: "Tank",
    },
    {
        id: 2,
        name: "Zed",
        title: "Maître des Ombres",
        image: "lien_vers_image_ahri",
        description: "L'impitoyable Zed est le maître de l'Ordre de l'ombre, une organisation qu'il a créée dans l'intention de militariser la tradition des arts martiaux d'Ionia et de chasser enfin les envahisseurs noxiens. Pendant la guerre, le désespoir le conduisit à déchaîner la Forme secrète de l'ombre, un puissant esprit maléfique aussi dangereux que corrompu. Si Zed maîtrise ces techniques interdites, c'est pour détruire tout ce qu'il considère comme une menace contre sa nation ou son ordre.",
        difficulty: "Modérée",
        category: "Assassin",
    },
    {
        id: 2,
        name: "Zeri",
        title: "Étincelle de Zaun",
        image: "lien_vers_image_ahri",
        description: "Zeri est une jeune femme vive et téméraire originaire des quartiers défavorisés de Zaun. Elle canalise son électricité intérieure afin de la charger dans un fusil conçu spécialement pour elle. Son pouvoir magique est le reflet de ses émotions, et ses étincelles sont aussi fulgurantes que son caractère. Résolument tournée vers les autres, Zeri se sert de son amour pour sa famille et son quartier durant chaque combat. Malgré toute sa bonne volonté, cependant, les événements ne se passent pas toujours comme prévu. Cela dit, Zeri est sûre d'une chose : si vous vous battez pour votre communauté, elle se battra avec vous.",
        difficulty: "Modérée",
        category: "Tireur",
    },
    {
        id: 2,
        name: "Ziggs",
        title: "Expert des Hexplosifs",
        image: "lien_vers_image_ahri",
        description: "Amoureux des grosses bombes et des mèches courtes, le yordle Ziggs est une force de la nature explosive. Assistant d'un inventeur de Piltover, il finit par se lasser de sa vie routinière et devint l'ami d'une jeune fille imprévisible et portée sur les explosifs, Jinx. Après une folle nuit en ville, Ziggs suivit les conseils de Jinx et s'installa à Zaun, où il se livre désormais à sa passion plus librement, terrorisant les Barons de la chimie comme les simples citoyens dans sa quête éternelle pour faire sauter tout ce qui traverse son champ de vision.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Zilean",
        title: "Gardien du temps",
        image: "lien_vers_image_ahri",
        description: "Naguère puissant mage d'Icathia, Zilean devint obsédé par le passage du temps après avoir assisté à la destruction de sa terre natale par le Néant. Refusant de perdre une minute à pleurer sur les décombres, il fit appel à une antique force magique capable de prédire tous les avenirs possibles. Devenu techniquement immortel, Zilean erre désormais entre passé, présent et futur, distordant autour de lui le flux du temps, toujours à la recherche du moment exact qui lui permettra de changer le passé et d'empêcher la destruction d'Icathia.",
        difficulty: "Modérée",
        category: "Support",
    },
    {
        id: 2,
        name: "Zoé",
        title: "Manifestation du Crépuscule",
        image: "lien_vers_image_ahri",
        description: "Incarnation de l'espièglerie, de l'imagination et de l'inconstance, Zoé est une messagère cosmique de Targon, annonciatrice des grands événements qui chamboulent les mondes. Sa simple présence distord les règles mathématiques qui gouvernent dans l'ombre les réalités et, sans pour autant le vouloir, peut même provoquer des cataclysmes. Cela explique peut-être la nonchalance désinvolte avec laquelle Zoé traite ses tâches, préférant consacrer le plus clair de son temps à s'amuser, à jouer des tours aux mortels, bref, à faire tout ce qui lui plaît. Une rencontre avec Zoé peut se révéler joyeuse et porteuse d'optimisme, mais ce n'est souvent qu'une apparence, cachant une vérité extrêmement dangereuse.",
        difficulty: "Modérée",
        category: "Mage",
    },
    {
        id: 2,
        name: "Zyra",
        title: "Dame aux Ronces",
        image: "lien_vers_image_ahri",
        description: "Née au cours d'une ancienne catastrophe magique, Zyra est la colère de la nature incarnée : mélange de plante et d'humain, faisant émerger de nouvelles pousses à chaque pas. Elle considère les nombreux mortels de Valoran comme de simples proies pour sa progéniture végétale, et les éliminer avec ses gerbes d'épines ne lui pose aucun problème. Bien que nul ne connaisse ses vrais objectifs, Zyra erre de par le monde, suivant son instinct qui est de coloniser toujours plus de terres et d'en exterminer toutes les autres formes de vie.",
        difficulty: "Modérée",
        category: "Mage",
    },
    // Ajoutez d'autres champions selon le besoin
];

export default championsData;
